name: toad_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  gap: ^3.0.1
  get_it: ^7.7.0
  go_router: ^14.1.0
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  injectable: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.3
  roundcheckbox: ^2.0.5
  toastification: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
